id = "cypher"
name = "Cypher"
version = "0.0.1"
schema_version = 1
authors = ["Hari Bantwal <hpai.bantwal@gmail.com>"]
description = "Zed Extension for cypher"
repository = "https://github.com/pupli/cypher"

[grammars.cypher]
repository = "https://github.com/pupli/tree-sitter-cypher"
commit = "a50f6fa0d4111c998a7faadb29d94246147c8318"
