id = "cypher"
name = "Cypher"
version = "0.0.1"
schema_version = 1
authors = ["Hari Bantwal <hpai.bantwal@gmail.com>"]
description = "Zed Extension for cypher"
repository = "https://github.com/pupli/cypher"

[grammars.cypher]
repository = "https://github.com/pupli/tree-sitter-cypher"
commit = "da995465375e4f8fd9b0aec42e1a402022053191"
